name: AI Test and Doc Suggestions

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  suggest-tests-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
    - name: Get PR Diff
      run: |
        git fetch origin ${{ github.base_ref }} --depth=1
        git diff --unified=0 origin/${{ github.base_ref }}...HEAD > pr.diff

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Backend Dependencies
      run: pip install -r requirements.txt

    - name: Run Backend Tests and Coverage
      run: pytest --cov=. --maxfail=1 --disable-warnings > pytest-report.txt

    - name: Generate AI Suggestions
      run: python generate_suggestions.py
      env:
        PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

    - name: Post PR Suggestion Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: "🤖 AI Suggestions"
        message: |
          $(cat suggestions.txt)

    # Only include if you use Django + DRF Spectacular
    # - name: Export OpenAPI Spec
    #   run: python manage.py spectacular --file openapi.yaml
